AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  EncryptedSignalFxAuthToken:
    Type: String
  SelectedMetricGroups:
    Type: String
  KeyId:
    Type: String
Resources:
  SignalFxProcessRDSMetricsEncrypted:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_script.lambda_handler
      Runtime: python2.7
      CodeUri: s3://signalfx-lambda-sam/enhanced_rds.zip
      Description: Parses RDS Enhanced Monitoring data from CloudWatch Logs and sends it to SignalFx.
      Timeout: 5
      Environment:
        Variables:
          encrypted_access_token:
            Ref: EncryptedSignalFxAuthToken
          groups:
            Ref: SelectedMetricGroups
          realm:
            Ref: Realm
      Policies:
        - KMSDecryptPolicy:
            KeyId:
              Ref: KeyId
